package org.danbrown.naniiro;

import android.graphics.ColorSpace;

class ColorSets {
    static class ColorSet {
        String ColorName;
        int ColorRGB;

        ColorSet(String name, int RGB) {
            this.ColorName = name;
            this.ColorRGB = RGB;
        }
    }

    static ColorSet[] X11Colors = {
            new ColorSet("Alice Blue", 0xfff0f8ff),
            new ColorSet("Antique White", 0xfffaebd7),
            new ColorSet("Aquamarine", 0xff7fffd4),
            new ColorSet("Azure", 0xfff0ffff),
            new ColorSet("Beige", 0xfff5f5dc),
            new ColorSet("Bisque", 0xffffe4c4),
            new ColorSet("Black", 0xff000000),
            new ColorSet("Blanched Almond", 0xffffebcd),
            new ColorSet("Blue", 0xff0000ff),
            new ColorSet("Blue Violet", 0xff8a2be2),
            new ColorSet("Brown", 0xffa52a2a),
            new ColorSet("Burlywood", 0xffdeb887),
            new ColorSet("Cadet Blue", 0xff5f9ea0),
            new ColorSet("Chartreuse", 0xff7fff00),
            new ColorSet("Chocolate", 0xffd2691e),
            new ColorSet("Coral", 0xffff7f50),
            new ColorSet("Cornflower Blue", 0xff6495ed),
            new ColorSet("Cornsilk", 0xfffff8dc),
            new ColorSet("Crimson", 0xffdc143c),
            new ColorSet("Cyan", 0xff00ffff),
            new ColorSet("Dark Blue", 0xff00008b),
            new ColorSet("Dark Cyan", 0xff008b8b),
            new ColorSet("Dark Goldenrod", 0xffb8860b),
            new ColorSet("Dark Gray", 0xffa9a9a9),
            new ColorSet("Dark Green", 0xff006400),
            new ColorSet("Dark Khaki", 0xffbdb76b),
            new ColorSet("Dark Magenta", 0xff8b008b),
            new ColorSet("Dark Olive Green", 0xff556b2f),
            new ColorSet("Dark Orange", 0xffff8c00),
            new ColorSet("Dark Orchid", 0xff9932cc),
            new ColorSet("Dark Red", 0xff8b0000),
            new ColorSet("Dark Salmon", 0xffe9967a),
            new ColorSet("Dark Sea Green", 0xff8fbc8f),
            new ColorSet("Dark Slate Blue", 0xff483d8b),
            new ColorSet("Dark Slate Gray", 0xff2f4f4f),
            new ColorSet("Dark Turquoise", 0xff00ced1),
            new ColorSet("Dark Violet", 0xff9400d3),
            new ColorSet("Deep Pink", 0xffff1493),
            new ColorSet("Deep Sky Blue", 0xff00bfff),
            new ColorSet("Dim Gray", 0xff696969),
            new ColorSet("Dodger Blue", 0xff1e90ff),
            new ColorSet("Firebrick", 0xffb22222),
            new ColorSet("Floral White", 0xfffffaf0),
            new ColorSet("Forest Green", 0xff228b22),
            new ColorSet("Gainsboro", 0xffdcdcdc),
            new ColorSet("Ghost White", 0xfff8f8ff),
            new ColorSet("Gold", 0xffffd700),
            new ColorSet("Goldenrod", 0xffdaa520),
            new ColorSet("Gray", 0xffbebebe),
            new ColorSet("Web Gray", 0xff808080),
            new ColorSet("Green", 0xff00ff00),
            new ColorSet("Web Green", 0xff008000),
            new ColorSet("Green Yellow", 0xffadff2f),
            new ColorSet("Honeydew", 0xfff0fff0),
            new ColorSet("Hot Pink", 0xffff69b4),
            new ColorSet("Indian Red", 0xffcd5c5c),
            new ColorSet("Indigo", 0xff4b0082),
            new ColorSet("Ivory", 0xfffffff0),
            new ColorSet("Khaki", 0xfff0e68c),
            new ColorSet("Lavender", 0xffe6e6fa),
            new ColorSet("Lavender Blush", 0xfffff0f5),
            new ColorSet("Lawn Green", 0xff7cfc00),
            new ColorSet("Lemon Chiffon", 0xfffffacd),
            new ColorSet("Light Blue", 0xffadd8e6),
            new ColorSet("Light Coral", 0xfff08080),
            new ColorSet("Light Cyan", 0xffe0ffff),
            new ColorSet("Light Goldenrod", 0xffffec8b),
            new ColorSet("Light Gray", 0xffd3d3d3),
            new ColorSet("Light Green", 0xff90ee90),
            new ColorSet("Light Pink", 0xffffb6c1),
            new ColorSet("Light Salmon", 0xffffa07a),
            new ColorSet("Light Sea Green", 0xff20b2aa),
            new ColorSet("Light Sky Blue", 0xff87cefa),
            new ColorSet("Light Slate Gray", 0xff778899),
            new ColorSet("Light Steel Blue", 0xffb0c4de),
            new ColorSet("Light Yellow", 0xffffffe0),
            new ColorSet("Lime Green", 0xff32cd32),
            new ColorSet("Linen", 0xfffaf0e6),
            new ColorSet("Magenta", 0xffff00ff),
            new ColorSet("Maroon", 0xffb03060),
            new ColorSet("Web Maroon", 0xff800000),
            new ColorSet("Medium Aquamarine", 0xff66cdaa),
            new ColorSet("Medium Blue", 0xff0000cd),
            new ColorSet("Medium Orchid", 0xffba55d3),
            new ColorSet("Medium Purple", 0xff9370db),
            new ColorSet("Medium Sea Green", 0xff3cb371),
            new ColorSet("Medium Slate Blue", 0xff7b68ee),
            new ColorSet("Medium Spring Green", 0xff00fa9a),
            new ColorSet("Medium Turquoise", 0xff48d1cc),
            new ColorSet("Medium Violet Red", 0xffc71585),
            new ColorSet("Midnight Blue", 0xff191970),
            new ColorSet("Mint Cream", 0xfff5fffa),
            new ColorSet("Misty Rose", 0xffffe4e1),
            new ColorSet("Moccasin", 0xffffe4b5),
            new ColorSet("Navajo White", 0xffffdead),
            new ColorSet("Navy Blue", 0xff000080),
            new ColorSet("Old Lace", 0xfffdf5e6),
            new ColorSet("Olive", 0xff808000),
            new ColorSet("Olive Drab", 0xff6b8e23),
            new ColorSet("Orange", 0xffffa500),
            new ColorSet("Orange Red", 0xffff4500),
            new ColorSet("Orchid", 0xffda70d6),
            new ColorSet("Pale Goldenrod", 0xffeee8aa),
            new ColorSet("Pale Green", 0xff98fb98),
            new ColorSet("Pale Turquoise", 0xffafeeee),
            new ColorSet("Pale Violet Red", 0xffdb7093),
            new ColorSet("Papaya Whip", 0xffffefd5),
            new ColorSet("Peach Puff", 0xffffdab9),
            new ColorSet("Peru", 0xffcd853f),
            new ColorSet("Pink", 0xffffc0cb),
            new ColorSet("Plum", 0xffdda0dd),
            new ColorSet("Powder Blue", 0xffb0e0e6),
            new ColorSet("Purple", 0xffa020f0),
            new ColorSet("Web Purple", 0xff800080),
            new ColorSet("Rebecca Purple", 0xff663399),
            new ColorSet("Red", 0xffff0000),
            new ColorSet("Rosy Brown", 0xffbc8f8f),
            new ColorSet("Royal Blue", 0xff4169e1),
            new ColorSet("Saddle Brown", 0xff8b4513),
            new ColorSet("Salmon", 0xfffa8072),
            new ColorSet("Sandy Brown", 0xfff4a460),
            new ColorSet("Sea Green", 0xff54ff9f),
            new ColorSet("Seashell", 0xfffff5ee),
            new ColorSet("Sienna", 0xffa0522d),
            new ColorSet("Silver", 0xffc0c0c0),
            new ColorSet("Sky Blue", 0xff87ceeb),
            new ColorSet("Slate Blue", 0xff6a5acd),
            new ColorSet("Slate Gray", 0xff708090),
            new ColorSet("Snow", 0xfffffafa),
            new ColorSet("Spring Green", 0xff00ff7f),
            new ColorSet("Steel Blue", 0xff4682b4),
            new ColorSet("Tan", 0xffd2b48c),
            new ColorSet("Teal", 0xff008080),
            new ColorSet("Thistle", 0xffd8bfd8),
            new ColorSet("Tomato", 0xffff6347),
            new ColorSet("Turquoise", 0xff40e0d0),
            new ColorSet("Violet", 0xffee82ee),
            new ColorSet("Wheat", 0xfff5deb3),
            new ColorSet("White", 0xffffffff),
            new ColorSet("White Smoke", 0xfff5f5f5),
            new ColorSet("Yellow", 0xffffff00),
            new ColorSet("Yellow Green", 0xff9acd32)
    };
}